# Google Cloud Build configuration for StellarForge Analytics API
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/stellarforge-api:$COMMIT_SHA", "."]

  # Push the container image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/stellarforge-api:$COMMIT_SHA"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "stellarforge-api"
      - "--image=gcr.io/$PROJECT_ID/stellarforge-api:$COMMIT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--concurrency=100"
      - "--max-instances=10"
      - "--port=8000"
      - "--update-secrets=LOG_LEVEL=log-level:latest"
      - "--update-secrets=PRICE_UPDATE_INTERVAL=price-update-interval:latest"
      - "--update-secrets=DATABASE_URL=database-url:latest"
      - "--update-secrets=STELLAR_NETWORK_URL=stellar-network-url:latest"
      - "--update-secrets=API_SECRET_KEY=api-secret-key:latest"

# Store images in Google Container Registry
images:
  - "gcr.io/$PROJECT_ID/stellarforge-api:$COMMIT_SHA"

# Available secrets (these need to be created in Secret Manager)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/log-level/versions/latest
      env: "LOG_LEVEL"
    - versionName: projects/$PROJECT_ID/secrets/price-update-interval/versions/latest
      env: "PRICE_UPDATE_INTERVAL"
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: "DATABASE_URL"
    - versionName: projects/$PROJECT_ID/secrets/stellar-network-url/versions/latest
      env: "STELLAR_NETWORK_URL"
    - versionName: projects/$PROJECT_ID/secrets/api-secret-key/versions/latest
      env: "API_SECRET_KEY"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
